### PR TITLE
Add keyboard controls to search.

### PR DESCRIPTION
**Pull request by exoego**
This PR introduces keyboad controls to the search bar.

1. `Escape` to close search. 
2. `Down` or `Tab` to move down in the seached functions, and  `Up` or `Shift+Tab` to move up.
3. `Enter` to open the selected function.

search-keybinds

### CODE REVIEW

**Comment by superruzafa** [comment]
Thanks for this great contribution.

It seems that the focused element is deselected when you release the Shift key (when moving up with ⇥). Can you review it?

**Comment by superruzafa** [comment]
Also, I don't know how hard is to scroll to the focused element when the selection goes beyond the viewport.
scroll-issue

**Comment by exoego** [comment]
Fixed the issues.
search-keybinds

**Comment by superruzafa** [comment]
Thanks!

**Pull request merged**
